os:
  - linux
  - windows

language: bash

services:
  - docker

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo snap install multipass --classic ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install multipass --version=0.9.0 ; fi

jobs:
  include:
    - name: "Unit Test"
      env: TEST_SUITE="ci/check_bats.bash unit"
    - name: "Integration Tests"
      env: TEST_SUITE="ci/check_bats.bash integration"

script: ci/check_bats.bash