os:
  - linux

language: bash

services:
  - docker

before_install:
  - snap install multipass

jobs:
  include:
    - name: "Unit Test"
      env: TEST_SUITE="ci/check_bats.bash unit"
    - name: "Integration Tests"
      env: TEST_SUITE="ci/check_bats.bash integration"

script: ci/check_bats.bash