os: linux
dist: bionic
language: bash

services:
  - docker
         
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo snap refresh ; fi
#  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo snap install multipass --classic ; fi

  include:
    - name: "Host Precondition"
      env: TEST_SUITE="host_precondition"
    - name: "Host Docker Precondition"
      env: TEST_SUITE="host_docker_precondition"
    - name: "Unit Test"
      env: TEST_SUITE="unit"
    - name: "Integration Tests"
      env: TEST_SUITE="integration"
    - name: "Docker Integration Test"
      env: TEST_SUITE="docker"

script: ci/check_bats.bash $TEST_SUITE
