os:
  - linux

language: bash

services:
  - docker

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo snap refresh && sudo snap install multipass --classic ; fi

jobs:
  include:
    - name: "Host Precondition"
      env: TEST_SUITE="host_precondition"
    - name: "Host Docker Precondition"
      env: TEST_SUITE="host_docker_precondition"
    - name: "Unit Test"
      env: TEST_SUITE="unit"
    - name: "Integration Tests"
      env: TEST_SUITE="integration"
    - name: "Docker Integration Test"
      env: TEST_SUITE="docker"
#    - name: "API Test"
#      env: TEST_SUITE="api"

script: ci/check_bats.bash $TEST_SUITE