version: "3.7"

services:
  grafana:
    image: grafana/grafana:master
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
        GF_SECURITY_ADMIN_USER: "admin"
        GF_SECURITY_ADMIN_PASSWORD: "admin"
        GF_PATHS_PROVISIONING: "/config/provisioning"
    volumes:
        - ./config/grafana:/config
        - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini
    networks:
      - loki
    labels:
      - traefik.enable=true
      - traefik.backend=grafana
      # Reverse proxy configuration - expose the container port
      - traefik.http.services.grafana.loadbalancer.server.port=9040
      - traefik.http.services.grafana.loadbalancer.passhostheader=true
      # SSL configuration
      - traefik.http.routers.grafana-ssl.entryPoints=https
      - traefik.http.routers.grafana-ssl.rule=host(`portainer.${BASE_DOMAIN}`)
      - traefik.http.routers.grafana-ssl.tls=true
      - traefik.http.routers.grafana-ssl.tls.certResolver=le
