version: "3.7"
services:
  traefik-fa:
    #image: thomseddon/traefik-forward-auth:2
    image: rajasoun/traefik-forward-auth:latest
    # OIDC Crendentials
    env_file:
      - ./config/secrets/oidc.env
    container_name: traefik-fa
    volumes:
      # configure oauth forwarder
      - ./config/traefik/forward.ini:/forward.ini
    environment:
      - CONFIG=/forward.ini
#      - default-provider=${DEFAULT_PROVIDER}
#      - providers.oidc.issuer-url=${PROVIDERS_OIDC_ISSUER_URL}
#      - providers.oidc.client-id=${PROVIDERS_OIDC_CLIENT_ID}
#      - providers.oidc.client-secret=${PROVIDERS_OIDC_CLIENT_SECRET}
    networks:
      - traefik
    labels:
      - traefik.enable=true
      # Which network traefik should listen on
      - traefik.docker.network=${DOCKER_NETWORK}
      - traefik.backend=traefik-fa
      - traefik.http.services.traefik-fa.loadBalancer.server.port=4181
      # SSL configuration
      - traefik.http.routers.traefik-fa-ssl.entryPoints=https
      - traefik.http.routers.traefik-fa-ssl.rule=host(`auth.${BASE_DOMAIN}`)
      - traefik.http.routers.traefik-fa-ssl.middlewares=sso@file
      - traefik.http.routers.traefik-fa-ssl.tls=true
      - traefik.http.routers.traefik-fa-ssl.tls.certResolver=le

networks:
  traefik: