---

- name: Environment Automation
  hosts: all
  any_errors_fatal: true
  max_fail_percentage: 0
  gather_facts: yes
  become: yes

  tasks:
    - name: View Current Distro on  {{ ansible_hostname }}
      shell: cat /etc/os-release
      register: distro
    - debug: var=distro