---

- name: Environment Automation
  hosts: all
  any_errors_fatal: true
  max_fail_percentage: 0
  gather_facts: yes
  become: yes

  vars_files:
    - vars/lynis.yml

  pre_tasks:
    - name: check apt last update
      stat: path=/var/cache/apt
      register: apt_cache_stat
    - name: update apt if needed # Update if not modified since the last 12 hours
      apt: update_cache=yes
      when: ansible_date_time.epoch|float - apt_cache_stat.stat.mtime > 60*60*12
    - name: Install the package "python-netaddr" # Dependency for Docker Hardening on Controller
      apt:
        name: python-netaddr
    - name: Set discovered Ansible Python interpreter.
      set_fact:
        ansible_python_interpreter: "{{ ansible_facts.python.executable }}"
      when: ansible_python_interpreter is not defined

  roles:
    - role: sa-secure-audit-lynis

  post_tasks:
    - name: Post Task Completion Message
      shell:
        echo 'I":" Done configuring the VM ...'
