apiVersion: 1

datasources:
- name: loki
  access: proxy
  type: loki
  url: http://loki:3100
  isDefault: true
  database: ''
  user: ''
  password: ''
  basicAuth: false
  id: 1
  orgId: 1
  readOnly: false
  jsonData:
    keepCookies: []

