name: CI

on: [push]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Run a one-line script
      run: brew cask install multipass
      
    - name: Run Unit Tests
      run: |
        echo UnitTests,
        ci/check_bats.bash unit
        
    - name: Run Integration Tests
      run: |
        echo Integration Test,
        ci/check_bats.bash integration
        
