name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: macOS
        if: startsWith(runner.os, 'macOS')
        uses: actions/checkout@v1
        run: |
          brew cask install docker
          brew  install bats
          git submodule update --init --recursive --remote

      - name: Linux
        if: startsWith(runner.os, 'Linux')
        uses: actions/checkout@v1
        run: |
          sudo snap install multipass --classic
          sudo snap install docker
          git submodule update --init --recursive --remote

      - name: Windows
        if: startsWith(runner.os, 'Windows')
        uses: actions/checkout@v1
        run: |
          iwr -useb get.scoop.sh | iex
          echo "::add-path::C:\Users\runneradmin\scoop\shims"
          scoop install git
          scoop install docker
          git submodule update --init --recursive --remote

