name: CI

on: [push]

jobs:
  validate:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Init & Update Submodules
        run: git submodule update --init --recursive --remote

      - name: Install Pre-Requisites macOS
        if: startsWith(runner.os, 'macOS')
        run: |
          brew cask install multipass
          brew install coreutils
          brew install bats
          alias readlink=greadlink

      - name: Install Pre-Requisites Linux
        if: startsWith(runner.os, 'Linux')
        run: |
          sudo add-apt-repository ppa:duggan/bats
          sudo apt-get update
          sudo apt-get install bats
          sudo snap install multipass --classic
          sudo snap install docker

      - name: Install Pre-Requisites Windows
        if: startsWith(runner.os, 'Windows')
        run: |
          iwr -useb get.scoop.sh | iex
          echo "::add-path::C:\Users\runneradmin\scoop\shims"
          npm install -g bats
          scoop install git
          scoop install docker

      ## Not the ci/check_bats.bash do not send the failures to the GitHub Actions
      - name: Test
        shell: bash
        run: |
          ci/check_bats.bash host_pre_condition
          bats test/unit/*.bats -t
          bats test/integration/test_integration*.bats -t

      ### @TODO: Test suite for  Docker yet to be ported for Mac & Windows
      ### Its due to the Limitation of GitHub Default Runners
      ### Mac: https://github.community/t5/GitHub-Actions/Why-is-Docker-not-installed-on-macOS/m-p/39364
      ### Windows : https://github.community/t5/GitHub-Actions/How-to-use-Linux-Docker-container-on-Windows-VM/m-p/38535
      ### Paid Self Hosted Runner is Required - so the Technical Debit is Parked
      ### bash -c "ci/check_bats.bash   -f .docker"
      - name: Docker Integration Test (Linux)
        if: startsWith(runner.os, 'Linux')
        run: |
          bats test/integration/test_docker*.bats  -t
          bats test/pre_conditions/test_docker*.bats -t


