# test
name: CI

on: [push]

jobs:

#  linux:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Install Multipass
#        run: sudo snap install multipass --classic
#      - name: Install Docker
#        run: sudo snap install docker
#      - name: Checkout Repository
#        uses: actions/checkout@v1
#      - name: Init & Update Submodules
#        run: git submodule update --init --recursive --remote
#      - name: Unit Test
#        run:  bash -c "ci/check_bats.bash unit"
#      - name: Integration Test
#        run:  bash -c "ci/check_bats.bash  integration"

  # macos:
  #   runs-on: macos-latest
  #   steps:
  #     - name: Install Multipass
  #       run: brew cask install multipass 
  #     - name: Install Docker
  #       run: brew cask install docker
  #     - name: Install BATS
  #       run: brew  install bats
  #     - name: Checkout
  #       uses: actions/checkout@v1
  #     - name: Checkout Submodules
  #       run: git submodule update --init --recursive --remote
  #     - name: Unit Test
  #       run:  bats test/test_unit*.bats

  windows:
    runs-on: windows-latest
    steps:
      - name: Install SCOOP
        run: iwr -useb get.scoop.sh | iex
      - name: Add SCOOP to the PATH
        run: echo "::add-path::C:\Users\runneradmin\scoop\shims"
        if: matrix.os == 'windows'
      - name: Install Git Bash
        run : scoop install git
#      - name: Install Docker Desktop
#        run: scoop bucket add dev-box-bucket https://github.com/rajasoun/dev-box-bucket; scoop install docker_desktop
#      - name: Checkout Repository
#        uses: actions/checkout@v1
#      - name: Init & Update Submodules
#        run: git submodule update --init --recursive --remote
#      - name: Unit Test
#        run: bash -c "ci/check_bats.bash unit"
#      - name: Integration Test
#        run:  bash -c "ci/check_bats.bash  integration"




