# test
name: CI

on: [push]

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install Multipass
        run: sudo snap install multipass --classic
      - name: Install Multipass
        run: sudo snap install docker
      - name: Checkout
        uses: actions/checkout@v1
      - name: Checkout Submodules
        run: git submodule update --init --recursive --remote
      - name: Test
        run:  bash -c "ci/check_bats.bash unit"

  macos:
    runs-on: macos-latest
    steps:
      - name: Install Multipass
        run: brew cask install multipass
      - name: Install BATS
        run: brew  install bats
      - name: Checkout
        uses: actions/checkout@v1
      - name: Checkout Submodules
        run: git submodule update --init --recursive --remote
      - name: Test
        #run: bash -c " function readlink() { DIR="${1%/*}"; (cd "$DIR" && echo "$(pwd -P)") } && ci/check_bats.bash"
        run:  bats test/test_unit*.bats

  install_windows:
    runs-on: windows-latest
    steps:
      - name: Install Multipass
        run: choco install git.portable
      - name: Checkout
        uses: actions/checkout@v1
      - name: Checkout Submodules
        run: git submodule update --init --recursive --remote
      - name: Test
        run: bash -c "ci/check_bats.bash unit"




