# test
name: CI

on: [push]

jobs:
  checkout:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Checkout Submodules
        run: git submodule update --init --recursive --remote

      - name: Wait for Checkout to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: checkout
          ref: github.event.pull_request.head.sha || github.sha

  install_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install Multipass
        run: sudo snap install multipass --classic

#  install_windows:
#    runs-on: windows-latest
#    steps:
#      - name: Install Multipass
#        run: choco install multipass --version=0.9.0

  install_macos:
    runs-on: macos-latest
    steps:
      - name: Install Multipass
        run: brew cask install multipass

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Test
        if: steps.wait-for-build.outputs.conclusion == 'success'
        uses: skx/github-action-tester@master
        with:
          script: ci/check_bats.bash

