name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Init & Update Submodules
        run: git submodule update --init --recursive --remote

      - name: macOS
        if: startsWith(runner.os, 'macOS')
        run: |
          brew cask install docker
          brew  install bats
          bats test/test_unit*.bats
          bats test/test_integ*.bats

      - name: Linux
        if: startsWith(runner.os, 'Linux')
        run: |
          sudo snap install multipass --classic
          sudo snap install docker
          bash -c "ci/check_bats.bash unit"
          bash -c "ci/check_bats.bash  integration"

      - name: Windows
        if: startsWith(runner.os, 'Windows')
        run: |
          iwr -useb get.scoop.sh | iex
          echo "::add-path::C:\Users\runneradmin\scoop\shims"
          scoop install git
          scoop install docker
          bash -c "ci/check_bats.bash unit"
          bash -c "ci/check_bats.bash  integration"

