# test
name: CI

on: [push]

jobs:

  install_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install Multipass
        run: sudo snap install multipass --classic

  #  install_windows:
  #    runs-on: windows-latest
  #    steps:
  #      - name: Install Multipass
  #        run: choco install multipass --version=0.9.0

  install_macos:
    runs-on: macos-latest
    steps:
      - name: Install Multipass
        run: brew cask install multipass

  checkout:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Checkout Submodules
        run: git submodule update --init --recursive --remote

      - name: Test
        uses: actions/github-script@0.5.0
        with:
          script: ci/check_bats.bash



