name: CI

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Checkout submodules
        run: git submodule update --init --recursive --remote

      - name: Install Multipass
        run: brew cask install multipass
      
      - name: Run Unit Tests
        run: ./test/libs/bats/bin/bats test/test_unit_*.bats

      - name: Run Integration Tests
        run: |
          echo Integration Test,
          test/test_integ*.bats
        
