name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: macOS - Setup Prerequisites
        if: startsWith(runner.os, 'macOS')
        run: |
          brew cask install docker
          brew  install bats

      - name: Linux - Setup Prerequisites
        if: startsWith(runner.os, 'Linux')
        run: |
          sudo snap install multipass --classic
          sudo snap install docker

      - name: Windows - Setup Prerequisites
        if: startsWith(runner.os, 'Windows')
        run: |
          iwr -useb get.scoop.sh | iex
          echo "::add-path::C:\Users\runneradmin\scoop\shims"
          scoop install git
          scoop install docker

      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Init & Update Submodules
        run: git submodule update --init --recursive --remote

      - name: Unit Test
        run:  bash -c "ci/check_bats.bash unit"
      - name: Integration Test
        run:  bash -c "ci/check_bats.bash  integration"