name: CI

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Checkout submodules
        run: git submodule update --init --recursive --remote

      - name: Install Multipass and bats-core
        run: brew cask install multipass bats-core
      
      - name: Run Unit Tests
        run: ci/check_bats.bash unit

      - name: Run Integration Tests
        run: |
          echo Integration Test,
          ci/check_bats.bash integration
        
